version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senhasegura
      MYSQL_DATABASE: livraria
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./bd/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./bd/script.sql:/docker-entrypoint-initdb.d/02-script.sql

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mysql
    ports:
      - "4444:4444"
    volumes:
      - ./backend/log:/log

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8000:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"

volumes:
  mysql_data: